FROM nginx:1.27-alpine

ENV NGINX_ENVSUBST_OUTPUT_DIR=/usr/share/nginx/html

COPY deploy/nginx-landing.conf /etc/nginx/conf.d/default.conf
COPY landing/ /usr/share/nginx/html/
COPY landing/index.html /etc/nginx/templates/index.html.template
