FROM python:3.12-slim
WORKDIR /app
COPY back/requirements.txt ./requirements.txt
COPY test/requirements-test.txt ./requirements-test.txt
RUN pip install --no-cache-dir -r requirements.txt -r requirements-test.txt \
    && playwright install --with-deps chromium
COPY back ./
COPY test ./test
CMD ["bash", "test/test.sh"]
