server {
    listen 80;
    server_name hand-in-hand-kzn.ru www.hand-in-hand-kzn.ru;
    client_max_body_size 20M;

    root /usr/share/nginx/html;
    index index.html;

    # сайт (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # всё остальное — на бэкенд
    location ~ ^/(api|uploads|admin|docs|openapi.json) {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}